# Generated by Django 4.2.4 on 2023-08-08 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SpareApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='item',
            new_name='part',
        ),
        migrations.RemoveField(
            model_name='product',
            name='issued_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='product',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='branch_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='part_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='issued_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
