# Generated by Django 4.2.4 on 2023-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpareApp', '0002_rename_item_sale_part_remove_product_issued_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
