# Generated by Django 4.2.4 on 2023-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpareApp', '0003_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='issued_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
