# Generated by Django 4.2.4 on 2023-08-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpareApp', '0004_product_issued_quantity_product_received_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
