# Generated by Django 4.2.4 on 2023-08-11 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SpareApp', '0005_alter_product_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
